version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_nest
    restart: unless-stopped
    environment:
      POSTGRES_USER: paclinjanja
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
